galaxy_info:
  author: Maximilian Frank
  description: This role can be used to pre configure owncloud users, groups and remote file system mounts
  company: AIT Austrian Institute of Technology
  license: GPL-3

  min_ansible_version: 2.10.0
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal

  galaxy_tags:
    - owncloud

dependencies: []
